version: '3.3'

services:
  db:
    image: postgres:10.1-alpine
    container_name: db
    env_file: .env.db
    expose:
      - 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    build:
      context: .
    container_name: app
    ports:
      - 8000:8000
    volumes:
      - .:/home/app/web
    depends_on:
      - db
    env_file: .env
    command: 'sh entrypoint.sh'
  
volumes:
  postgres_data: