# Generated by Django 3.2.7 on 2021-09-03 03:30

import desafio_dev.core.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CNABModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('file', models.FileField(upload_to=desafio_dev.core.models.documents_directory_path, verbose_name='Arquivo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('transaction_type', models.PositiveIntegerField(choices=[(1, 'Débito'), (2, 'Boleto'), (3, 'Financiamento'), (4, 'Crédito'), (5, 'Recebimento Empréstimo'), (6, 'Vendas'), (7, 'Recebimento TED'), (8, 'Recebimento DOC'), (9, 'Aluguel')], verbose_name='tipo de transação')),
                ('date', models.DateField(verbose_name='data')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('card', models.CharField(max_length=12, verbose_name='cartão')),
                ('hour', models.TimeField(verbose_name='hora')),
                ('owner', models.CharField(max_length=14, verbose_name='dono da loja')),
                ('store', models.CharField(max_length=19, verbose_name='nome da loja')),
            ],
            options={
                'verbose_name': 'Operação',
                'verbose_name_plural': 'Operações',
                'ordering': ['-created'],
            },
        ),
    ]
