# Generated by Django 3.2.7 on 2021-09-03 04:05

import desafio_dev.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnabmodel',
            name='file',
            field=models.FileField(upload_to=desafio_dev.core.models.documents_directory_path, validators=[desafio_dev.core.models.cnab_validator], verbose_name='Arquivo'),
        ),
    ]
